from datetime import datetime

area_dict = {}
aliyun_url = "https://ncovdata.market.alicloudapi.com/ncov/cityDiseaseInfoWithTrend"
backend_host = "http://39.106.140.102:27031"
world_dict = {}

country_dict_en = {
    'Afghanistan': '阿富汗',
    'Albania': '阿尔巴尼亚',
    'Algeria': '阿尔及利亚',
    'American Samoa': '东萨摩亚',
    'Andorra': '安道尔共和国',
    'Angola': '安哥拉',
    'Anguilla': '安圭拉岛',
    'Antigua and Barbuda': '安提瓜和巴布达',
    'Argentina': '阿根廷',
    'Armenia': '亚美尼亚',
    'Ascension': '阿森松',
    'Australia': '澳大利亚',
    'Austria': '奥地利',
    'Azerbaijan': '阿塞拜疆',
    'Bahamas': '巴哈马',
    'Bahrain': '巴林',
    'Bangladesh': '孟加拉国',
    'Barbados': '巴巴多斯',
    'Belarus': '白俄罗斯',
    'Belgium': '比利时',
    'Belize': '伯利兹',
    'Benin': '贝宁',
    'Bermuda Is': '百慕大群岛',
    'Bhutan': '不丹',
    'Bolivia': '玻利维亚',
    'Bosnia and Herzegovina': '波斯尼亚和黑塞哥维那',
    'Botswana': '博茨瓦纳',
    'Brazil': '巴西',
    'Brunei': '文莱',
    'Bulgaria': '保加利亚',
    'Burkina Faso': '布基纳法索',
    'Burma': '缅甸',
    'Burundi': '布隆迪',
    'Cabo Verde': '佛得角',
    'Cambodia': '柬埔寨',
    'Cameroon': '喀麦隆',
    'Canada': '加拿大',
    'Cayman Is': '开曼群岛',
    'Central African Republic': '中非共和国',
    'Chad': '乍得',
    'Chile': '智利',
    'China': '中国',
    'Colombia': '哥伦比亚',
    'Comoros': '科摩罗',
    'Congo': '刚果',
    'Congo (Brazzaville)': '刚果(布拉柴维尔)',
    'Congo (Kinshasa)': '刚果(金)',
    'Cook Is': '库克群岛',
    'Costa Rica': '哥斯达黎加',
    "Cote d'Ivoire": '科特迪瓦',
    'Croatia': '克罗地亚',
    'Cuba': '古巴',
    'Cyprus': '塞浦路斯',
    'Czech Republic': '捷克',
    'Czechia': '捷克',
    'Denmark': '丹麦',
    'Diamond Princess': '钻石公主号游轮',
    'Djibouti': '吉布提',
    'Dominica': '多米尼加',
    'Dominica Rep': '多米尼加共和国',
    'Dominican Republic': '多米尼加共和国',
    'EI Salvador': '萨尔瓦多',
    'Ecuador': '厄瓜多尔',
    'Egypt': '埃及',
    'El Salvador': '萨尔瓦多',
    'Equatorial Guinea': '赤道几内亚',
    'Eritrea': '厄立特里亚',
    'Estonia': '爱沙尼亚',
    'Eswatini': '埃斯瓦蒂尼',
    'Ethiopia': '埃塞俄比亚',
    'Fiji': '斐济',
    'Finland': '芬兰',
    'France': '法国',
    'French Guiana': '法属圭亚那',
    'French Polynesia': '法属玻利尼西亚',
    'Gabon': '加蓬',
    'Gambia': '冈比亚',
    'Georgia': '格鲁吉亚',
    'Germany': '德国',
    'Ghana': '加纳',
    'Gibraltar': '直布罗陀',
    'Greece': '希腊',
    'Grenada': '格林纳达',
    'Guam': '关岛',
    'Guatemala': '危地马拉',
    'Guinea': '几内亚',
    'Guinea-Bissau': '几内亚比绍',
    'Guyana': '圭亚那',
    'Haiti': '海地',
    'Holy See': '梵蒂冈',
    'Honduras': '洪都拉斯',
    'Hongkong': '香港',
    'Hong Kong': '香港',
    'Hungary': '匈牙利',
    'Iceland': '冰岛',
    'India': '印度',
    'Indonesia': '印度尼西亚',
    'Iran': '伊朗',
    'Iraq': '伊拉克',
    'Ireland': '爱尔兰',
    'Israel': '以色列',
    'Italy': '意大利',
    'Ivory Coast': '科特迪瓦',
    'Jamaica': '牙买加',
    'Japan': '日本',
    'Jordan': '约旦',
    'Kampuchea (Cambodia )': '柬埔寨',
    'Kampuchea': '柬埔寨',
    'Kazakhstan': '哈萨克斯坦',
    'Kazakstan': '哈萨克斯坦',
    'Kenya': '肯尼亚',
    'Kiribati': '基里巴斯',
    'Korea': '韩国',
    'South Korea': '韩国',
    'Korea, South': '韩国',
    'Kosovo': '科索沃',
    'Kuwait': '科威特',
    'Kyrgyzstan': '吉尔吉斯坦',
    'Laos': '老挝',
    'Latvia': '拉脱维亚',
    'Lebanon': '黎巴嫩',
    'Lesotho': '莱索托',
    'Liberia': '利比里亚',
    'Libya': '利比亚',
    'Liechtenstein': '列支敦士登',
    'Lithuania': '立陶宛',
    'Luxembourg': '卢森堡',
    'MS Zaandam': '尚丹号邮轮',
    'Macao': '澳门',
    'Macau': '澳门',
    'Madagascar': '马达加斯加',
    'Mainland China': '中国',
    'Malawi': '马拉维',
    'Malaysia': '马来西亚',
    'Maldives': '马尔代夫',
    'Mali': '马里',
    'Malta': '马耳他',
    'Mariana Is': '马里亚那群岛',
    'Marshall Islands': '马绍尔群岛',
    'Martinique': '马提尼克',
    'Mauritania': '毛里塔尼亚',
    'Mauritius': '毛里求斯',
    'Mexico': '墨西哥',
    'Micronesia': '密克罗尼西亚联邦',
    'Moldova': '摩尔多瓦',
    'Monaco': '摩纳哥',
    'Mongolia': '蒙古',
    'Montenegro': '黑山共和国',
    'Montserrat Is': '蒙特塞拉特岛',
    'Morocco': '摩洛哥',
    'Mozambique': '莫桑比克',
    'Namibia': '纳米比亚',
    'Nauru': '瑙鲁',
    'Nepal': '尼泊尔',
    'Netheriands Antilles': '荷属安的列斯',
    'Netherlands': '荷兰',
    'New Zealand': '新西兰',
    'Nicaragua': '尼加拉瓜',
    'Niger': '尼日尔',
    'Nigeria': '尼日利亚',
    'North Korea': '朝鲜',
    'North Macedonia': '北马其顿',
    'Norway': '挪威',
    'Oman': '阿曼',
    'Pakistan': '巴基斯坦',
    'Palau': '帕劳',
    'Panama': '巴拿马',
    'Papua New Cuinea': '巴布亚新几内亚',
    'Papua New Guinea': '巴布亚新几内亚',
    'Paraguay': '巴拉圭',
    'Peru': '秘鲁',
    'Philippines': '菲律宾',
    'Poland': '波兰',
    'Portugal': '葡萄牙',
    'Puerto Rico': '波多黎各',
    'Qatar': '卡塔尔',
    'Reunion': '留尼旺',
    'Romania': '罗马尼亚',
    'Russia': '俄罗斯',
    'Rwanda': '卢旺达',
    'Saint Kitts and Nevis': '圣基茨和尼维斯',
    'Saint Lucia': '圣卢西亚',
    'Saint Vincent': '圣文森特岛',
    'Saint Vincent and the Grenadines': '文森特和格林纳丁斯',
    'Samoa': '萨摩亚',
    'Samoa Eastern': '东萨摩亚(美)',
    'Samoa Western': '西萨摩亚',
    'San Marino': '圣马力诺',
    'Sao Tome and Principe': '圣多美和普林西比',
    'Saudi Arabia': '沙特阿拉伯',
    'Senegal': '塞内加尔',
    'Serbia': '塞尔维亚',
    'Seychelles': '塞舌尔',
    'Sierra Leone': '塞拉利昂',
    'Singapore': '新加坡',
    'Slovakia': '斯洛伐克',
    'Slovenia': '斯洛文尼亚',
    'Solomon Islands': '所罗门群岛',
    'Saint Helena Solomon Is': '圣赫勒拿所罗门群岛',
    'Somali': '索马里',
    'Somalia': '索马里',
    'South Africa': '南非',
    'South Sudan': '南苏丹',
    'Spain': '西班牙',
    'Sri Lanka': '斯里兰卡',
    'SriLanka': '斯里兰卡',
    'St.Lucia': '圣卢西亚',
    'St.Vincent': '圣文森特',
    'Sudan': '苏丹',
    'Summer Olympics 2020': '2020年夏季奥运会',
    'Suriname': '苏里南',
    'Swaziland': '斯威士兰',
    'Sweden': '瑞典',
    'Switzerland': '瑞士',
    'Syria': '叙利亚',
    'Taiwan': '台湾省',
    'Taiwan*': '台湾',
    'Tajikistan': '塔吉克斯坦',
    'Tanzania': '坦桑尼亚',
    'Thailand': '泰国',
    'Timor-Leste': '东帝汶',
    'Togo': '多哥',
    'Tonga': '汤加',
    'Trinidad and Tobago': '特立尼达和多巴哥',
    'Tunisia': '突尼斯',
    'Turkey': '土耳其',
    'Turkmenistan': '土库曼斯坦',
    'US': '美国',
    'United States': '美国',
    'Uganda': '乌干达',
    'Ukraine': '乌克兰',
    'United Arab Emirates': '阿拉伯联合酋长国',
    'United Kingdom': '英国',
    'United States of America': '美国',
    'USA': '美国',
    'Uruguay': '乌拉圭',
    'Uzbekistan': '乌兹别克斯坦',
    'Vanuatu': '瓦努阿图',
    'Venezuela': '委内瑞拉',
    'Vietnam': '越南',
    'West Bank and Gaza': '西岸和加沙',
    'W. Sahara': '撒哈拉',
    'Greenland': '格陵兰岛',
    'Yemen': '也门',
    'Yugoslavia': '南斯拉夫',
    'Zaire': '扎伊尔',
    'Zambia': '赞比亚',
    'Zimbabwe': '津巴布韦',
    'Aruba': '阿鲁巴', 'Bermuda': '百慕大', 'Bonaire Sint Eustatius and Saba': '博内尔圣尤斯特修斯和萨巴',
    'British Virgin Islands': '英属维尔京群岛', 'Cape Verde': '佛得角', 'Cayman Islands': '开曼群岛', 'Cook Islands': '库克群岛',
    'Curacao': '库拉索', 'Democratic Republic of Congo': '刚果民主共和国', 'Faeroe Islands': '法罗群岛', 'Falkland Islands': '福克兰群岛',
    'Guernsey': '根西岛', 'Isle of Man': '马恩岛', 'Jersey': '泽西岛', 'Micronesia (country)': '密克罗尼西亚', 'Montserrat': '蒙特塞拉特',
    'Myanmar': '缅甸', 'New Caledonia': '新喀里多尼亚', 'Northern Cyprus': '北塞浦路斯', 'Palestine': '巴勒斯坦', 'Pitcairn': '皮特凯恩',
    'Saint Helena': '圣赫勒拿', 'Sint Maarten (Dutch part)': '圣马丁岛', 'Timor': '帝汶', 'Turks and Caicos Islands': '特克斯和凯科斯群岛',
    'Tuvalu': '图瓦卢', 'Vatican': '梵蒂冈', 'Wallis and Futuna': '瓦利斯和富图纳'

}
# country_dict_cn = {}
# country_names_en = country_dict_en.keys()
# for name_en in country_names_en:
#     name_cn = country_dict_en.get(name_en)
#     name_list = country_dict_cn.get(name_cn, [])
#     name_list.append(name_en)
#     country_dict_cn[name_cn] = name_list
# print(country_dict_cn)

country_dict_cn = {'阿富汗': ['Afghanistan'], '阿尔巴尼亚': ['Albania'], '阿尔及利亚': ['Algeria'], '东萨摩亚': ['American Samoa'],
                   '安道尔共和国': ['Andorra'], '安哥拉': ['Angola'], '安圭拉岛': ['Anguilla'], '安提瓜和巴布达': ['Antigua and Barbuda'],
                   '阿根廷': ['Argentina'], '亚美尼亚': ['Armenia'], '阿森松': ['Ascension'], '澳大利亚': ['Australia'],
                   '奥地利': ['Austria'], '阿塞拜疆': ['Azerbaijan'], '巴哈马': ['Bahamas'], '巴林': ['Bahrain'],
                   '孟加拉国': ['Bangladesh'], '巴巴多斯': ['Barbados'], '白俄罗斯': ['Belarus'], '比利时': ['Belgium'],
                   '伯利兹': ['Belize'], '贝宁': ['Benin'], '百慕大群岛': ['Bermuda Is'], '不丹': ['Bhutan'], '玻利维亚': ['Bolivia'],
                   '波斯尼亚和黑塞哥维那': ['Bosnia and Herzegovina'], '博茨瓦纳': ['Botswana'], '巴西': ['Brazil'], '文莱': ['Brunei'],
                   '保加利亚': ['Bulgaria'], '布基纳法索': ['Burkina Faso'], '缅甸': ['Burma', 'Myanmar'], '布隆迪': ['Burundi'],
                   '佛得角': ['Cabo Verde', 'Cape Verde'], '柬埔寨': ['Cambodia', 'Kampuchea (Cambodia )', 'Kampuchea'],
                   '喀麦隆': ['Cameroon'], '加拿大': ['Canada'], '开曼群岛': ['Cayman Is', 'Cayman Islands'],
                   '中非共和国': ['Central African Republic'], '乍得': ['Chad'], '智利': ['Chile'],
                   '中国': ['China', 'Mainland China'], '哥伦比亚': ['Colombia'], '科摩罗': ['Comoros'], '刚果': ['Congo'],
                   '刚果(布拉柴维尔)': ['Congo (Brazzaville)'], '刚果(金)': ['Congo (Kinshasa)'],
                   '库克群岛': ['Cook Is', 'Cook Islands'], '哥斯达黎加': ['Costa Rica'],
                   '科特迪瓦': ["Cote d'Ivoire", 'Ivory Coast'], '克罗地亚': ['Croatia'], '古巴': ['Cuba'], '塞浦路斯': ['Cyprus'],
                   '捷克': ['Czech Republic', 'Czechia'], '丹麦': ['Denmark'], '钻石公主号游轮': ['Diamond Princess'],
                   '吉布提': ['Djibouti'], '多米尼加': ['Dominica'], '多米尼加共和国': ['Dominica Rep', 'Dominican Republic'],
                   '萨尔瓦多': ['EI Salvador', 'El Salvador'], '厄瓜多尔': ['Ecuador'], '埃及': ['Egypt'],
                   '赤道几内亚': ['Equatorial Guinea'], '厄立特里亚': ['Eritrea'], '爱沙尼亚': ['Estonia'], '埃斯瓦蒂尼': ['Eswatini'],
                   '埃塞俄比亚': ['Ethiopia'], '斐济': ['Fiji'], '芬兰': ['Finland'], '法国': ['France'],
                   '法属圭亚那': ['French Guiana'], '法属玻利尼西亚': ['French Polynesia'], '加蓬': ['Gabon'], '冈比亚': ['Gambia'],
                   '格鲁吉亚': ['Georgia'], '德国': ['Germany'], '加纳': ['Ghana'], '直布罗陀': ['Gibraltar'], '希腊': ['Greece'],
                   '格林纳达': ['Grenada'], '关岛': ['Guam'], '危地马拉': ['Guatemala'], '几内亚': ['Guinea'],
                   '几内亚比绍': ['Guinea-Bissau'], '圭亚那': ['Guyana'], '海地': ['Haiti'], '梵蒂冈': ['Holy See', 'Vatican'],
                   '洪都拉斯': ['Honduras'], '香港': ['Hongkong', 'Hong Kong'], '匈牙利': ['Hungary'], '冰岛': ['Iceland'],
                   '印度': ['India'], '印度尼西亚': ['Indonesia'], '伊朗': ['Iran'], '伊拉克': ['Iraq'], '爱尔兰': ['Ireland'],
                   '以色列': ['Israel'], '意大利': ['Italy'], '牙买加': ['Jamaica'], '日本': ['Japan'], '约旦': ['Jordan'],
                   '哈萨克斯坦': ['Kazakhstan', 'Kazakstan'], '肯尼亚': ['Kenya'], '基里巴斯': ['Kiribati'],
                   '韩国': ['Korea', 'South Korea', 'Korea, South'], '科索沃': ['Kosovo'], '科威特': ['Kuwait'],
                   '吉尔吉斯坦': ['Kyrgyzstan'], '老挝': ['Laos'], '拉脱维亚': ['Latvia'], '黎巴嫩': ['Lebanon'], '莱索托': ['Lesotho'],
                   '利比里亚': ['Liberia'], '利比亚': ['Libya'], '列支敦士登': ['Liechtenstein'], '立陶宛': ['Lithuania'],
                   '卢森堡': ['Luxembourg'], '尚丹号邮轮': ['MS Zaandam'], '澳门': ['Macao', 'Macau'], '马达加斯加': ['Madagascar'],
                   '马拉维': ['Malawi'], '马来西亚': ['Malaysia'], '马尔代夫': ['Maldives'], '马里': ['Mali'], '马耳他': ['Malta'],
                   '马里亚那群岛': ['Mariana Is'], '马绍尔群岛': ['Marshall Islands'], '马提尼克': ['Martinique'],
                   '毛里塔尼亚': ['Mauritania'], '毛里求斯': ['Mauritius'], '墨西哥': ['Mexico'], '密克罗尼西亚联邦': ['Micronesia'],
                   '摩尔多瓦': ['Moldova'], '摩纳哥': ['Monaco'], '蒙古': ['Mongolia'], '黑山共和国': ['Montenegro'],
                   '蒙特塞拉特岛': ['Montserrat Is'], '摩洛哥': ['Morocco'], '莫桑比克': ['Mozambique'], '纳米比亚': ['Namibia'],
                   '瑙鲁': ['Nauru'], '尼泊尔': ['Nepal'], '荷属安的列斯': ['Netheriands Antilles'], '荷兰': ['Netherlands'],
                   '新西兰': ['New Zealand'], '尼加拉瓜': ['Nicaragua'], '尼日尔': ['Niger'], '尼日利亚': ['Nigeria'],
                   '朝鲜': ['North Korea'], '北马其顿': ['North Macedonia'], '挪威': ['Norway'], '阿曼': ['Oman'],
                   '巴基斯坦': ['Pakistan'], '帕劳': ['Palau'], '巴拿马': ['Panama'],
                   '巴布亚新几内亚': ['Papua New Cuinea', 'Papua New Guinea'], '巴拉圭': ['Paraguay'], '秘鲁': ['Peru'],
                   '菲律宾': ['Philippines'], '波兰': ['Poland'], '葡萄牙': ['Portugal'], '波多黎各': ['Puerto Rico'],
                   '卡塔尔': ['Qatar'], '留尼旺': ['Reunion'], '罗马尼亚': ['Romania'], '俄罗斯': ['Russia'], '卢旺达': ['Rwanda'],
                   '圣基茨和尼维斯': ['Saint Kitts and Nevis'], '圣卢西亚': ['Saint Lucia', 'St.Lucia'],
                   '圣文森特岛': ['Saint Vincent'], '文森特和格林纳丁斯': ['Saint Vincent and the Grenadines'], '萨摩亚': ['Samoa'],
                   '东萨摩亚(美)': ['Samoa Eastern'], '西萨摩亚': ['Samoa Western'], '圣马力诺': ['San Marino'],
                   '圣多美和普林西比': ['Sao Tome and Principe'], '沙特阿拉伯': ['Saudi Arabia'], '塞内加尔': ['Senegal'],
                   '塞尔维亚': ['Serbia'], '塞舌尔': ['Seychelles'], '塞拉利昂': ['Sierra Leone'], '新加坡': ['Singapore'],
                   '斯洛伐克': ['Slovakia'], '斯洛文尼亚': ['Slovenia'], '所罗门群岛': ['Solomon Islands'],
                   '圣赫勒拿所罗门群岛': ['Saint Helena Solomon Is'], '索马里': ['Somali', 'Somalia'], '南非': ['South Africa'],
                   '南苏丹': ['South Sudan'], '西班牙': ['Spain'], '斯里兰卡': ['Sri Lanka', 'SriLanka'], '圣文森特': ['St.Vincent'],
                   '苏丹': ['Sudan'], '2020年夏季奥运会': ['Summer Olympics 2020'], '苏里南': ['Suriname'], '斯威士兰': ['Swaziland'],
                   '瑞典': ['Sweden'], '瑞士': ['Switzerland'], '叙利亚': ['Syria'], '台湾省': ['Taiwan'], '台湾': ['Taiwan*'],
                   '塔吉克斯坦': ['Tajikistan'], '坦桑尼亚': ['Tanzania'], '泰国': ['Thailand'], '东帝汶': ['Timor-Leste'],
                   '多哥': ['Togo'], '汤加': ['Tonga'], '特立尼达和多巴哥': ['Trinidad and Tobago'], '突尼斯': ['Tunisia'],
                   '土耳其': ['Turkey'], '土库曼斯坦': ['Turkmenistan'],
                   '美国': ['US', 'United States', 'United States of America', 'USA'], '乌干达': ['Uganda'],
                   '乌克兰': ['Ukraine'],
                   '阿拉伯联合酋长国': ['United Arab Emirates'], '英国': ['United Kingdom'], '乌拉圭': ['Uruguay'],
                   '乌兹别克斯坦': ['Uzbekistan'], '瓦努阿图': ['Vanuatu'], '委内瑞拉': ['Venezuela'], '越南': ['Vietnam'],
                   '西岸和加沙': ['West Bank and Gaza'], '撒哈拉': ['W. Sahara'], '格陵兰岛': ['Greenland'], '也门': ['Yemen'],
                   '南斯拉夫': ['Yugoslavia'], '扎伊尔': ['Zaire'], '赞比亚': ['Zambia'], '津巴布韦': ['Zimbabwe'], '阿鲁巴': ['Aruba'],
                   '百慕大': ['Bermuda'], '博内尔圣尤斯特修斯和萨巴': ['Bonaire Sint Eustatius and Saba'],
                   '英属维尔京群岛': ['British Virgin Islands'], '库拉索': ['Curacao'],
                   '刚果民主共和国': ['Democratic Republic of Congo'], '法罗群岛': ['Faeroe Islands'],
                   '福克兰群岛': ['Falkland Islands'], '根西岛': ['Guernsey'], '马恩岛': ['Isle of Man'], '泽西岛': ['Jersey'],
                   '密克罗尼西亚': ['Micronesia (country)'], '蒙特塞拉特': ['Montserrat'], '新喀里多尼亚': ['New Caledonia'],
                   '北塞浦路斯': ['Northern Cyprus'], '巴勒斯坦': ['Palestine'], '皮特凯恩': ['Pitcairn'], '圣赫勒拿': ['Saint Helena'],
                   '圣马丁岛': ['Sint Maarten (Dutch part)'], '帝汶': ['Timor'], '特克斯和凯科斯群岛': ['Turks and Caicos Islands'],
                   '图瓦卢': ['Tuvalu'], '瓦利斯和富图纳': ['Wallis and Futuna']}

province_dict_cn = {
    '安徽省': 'Anhui',
    '北京市': 'Beijing',
    '福建省': 'Fujian',
    '甘肃省': 'Gansu',
    '广东省': 'Guangdong',
    '广西壮族自治区': 'Guangxi',
    '贵州省': 'Guizhou',
    '海南省': 'Hainan',
    '河北省': 'Hebei',
    '河南省': 'Henan',
    '黑龙江省': 'Heilongjiang',
    '湖北省': 'Hubei',
    '湖南省': 'Hunan',
    '吉林省': 'Jilin',
    '江苏省': 'Jiangsu',
    '江西省': 'Jiangxi',
    '辽宁省': 'Liaoning',
    '内蒙古自治区': 'Inner Mongolia',
    '宁夏回族自治区': 'Ningxia',
    '青海省': 'Qinghai',
    '山东省': 'Shandong',
    '山西省': 'Shanxi',
    '陕西省': 'Shaanxi',
    '上海市': 'Shanghai',
    '四川省': 'Sichuan',
    '天津市': 'Tianjin',
    '西藏自治区': 'Tibet',
    '新疆维吾尔自治区': 'Xinjiang',
    '云南省': 'Yunnan',
    '浙江省': 'Zhejiang',
    '重庆市': 'Chongqing',
    '香港特别行政区': 'HongKong',
    '澳门特别行政区': 'Macao',
    '台湾省': 'Taiwan',
    '南海诸岛': 'South China Sea Islands'
}
# 根据省份英文取中文
province_dict_en = dict(zip(province_dict_cn.values(),
                            province_dict_cn.keys()))

province_code = [{"code": "110000", "name": "北京市"}, {"code": "120000", "name": "天津市"},
                 {"code": "130000", "name": "河北省"}, {"code": "140000", "name": "山西省"},
                 {"code": "150000", "name": "内蒙古自治区"}, {"code": "210000", "name": "辽宁省"},
                 {"code": "220000", "name": "吉林省"}, {"code": "230000", "name": "黑龙江省"},
                 {"code": "310000", "name": "上海市"}, {"code": "320000", "name": "江苏省"},
                 {"code": "330000", "name": "浙江省"}, {"code": "340000", "name": "安徽省"},
                 {"code": "350000", "name": "福建省"}, {"code": "360000", "name": "江西省"},
                 {"code": "370000", "name": "山东省"}, {"code": "410000", "name": "河南省"},
                 {"code": "420000", "name": "湖北省"}, {"code": "430000", "name": "湖南省"},
                 {"code": "440000", "name": "广东省"}, {"code": "450000", "name": "广西壮族自治区"},
                 {"code": "460000", "name": "海南省"}, {"code": "500000", "name": "重庆市"},
                 {"code": "510000", "name": "四川省"}, {"code": "520000", "name": "贵州省"},
                 {"code": "530000", "name": "云南省"}, {"code": "540000", "name": "西藏自治区"},
                 {"code": "610000", "name": "陕西省"}, {"code": "620000", "name": "甘肃省"},
                 {"code": "630000", "name": "青海省"}, {"code": "640000", "name": "宁夏回族自治区"},
                 {"code": "650000", "name": "新疆维吾尔自治区"}, {"code": "710000", "name": "台湾省"},
                 {"code": "810000", "name": "香港特别行政区"}, {"code": "820000", "name": "澳门特别行政区"}]
simple_province_name = [
    '安徽',
    '北京',
    '福建',
    '甘肃',
    '广东',
    '广西',
    '贵州',
    '海南',
    '河北',
    '河南',
    '黑龙江',
    '湖北',
    '湖南',
    '吉林',
    '江苏',
    '江西',
    '辽宁',
    '内蒙古',
    '宁夏',
    '青海',
    '山东',
    '山西',
    '陕西',
    '上海',
    '四川',
    '天津',
    '西藏',
    '新疆',
    '云南',
    '浙江',
    '重庆',
    '香港',
    '澳门',
    '台湾',
]

complex_province_name = [
    '安徽省',
    '北京市',
    '福建省',
    '甘肃省',
    '广东省',
    '广西壮族自治区',
    '贵州省',
    '海南省',
    '河北省',
    '河南省',
    '黑龙江省',
    '湖北省',
    '湖南省',
    '吉林省',
    '江苏省',
    '江西省',
    '辽宁省',
    '内蒙古自治区',
    '宁夏回族自治区',
    '青海省',
    '山东省',
    '山西省',
    '陕西省',
    '上海市',
    '四川省',
    '天津市',
    '西藏自治区',
    '新疆维吾尔自治区',
    '云南省',
    '浙江省',
    '重庆市',
    '香港特别行政区',
    '澳门特别行政区',
    '台湾省'
]

province_name_dict = dict(zip(simple_province_name, complex_province_name))

city_dict = {"110000": [{"code": "110100", "name": "直辖市"}], "120000": [{"code": "120100", "name": "直辖市"}],
             "130000": [{"code": "130100", "name": "石家庄市"}, {"code": "130200", "name": "唐山市"},
                        {"code": "130300", "name": "秦皇岛市"}, {"code": "130400", "name": "邯郸市"},
                        {"code": "130500", "name": "邢台市"}, {"code": "130600", "name": "保定市"},
                        {"code": "130700", "name": "张家口市"}, {"code": "130800", "name": "承德市"},
                        {"code": "130900", "name": "沧州市"}, {"code": "131000", "name": "廊坊市"},
                        {"code": "131100", "name": "衡水市"}],
             "140000": [{"code": "140100", "name": "太原市"}, {"code": "140200", "name": "大同市"},
                        {"code": "140300", "name": "阳泉市"}, {"code": "140400", "name": "长治市"},
                        {"code": "140500", "name": "晋城市"}, {"code": "140600", "name": "朔州市"},
                        {"code": "140700", "name": "晋中市"}, {"code": "140800", "name": "运城市"},
                        {"code": "140900", "name": "忻州市"}, {"code": "141000", "name": "临汾市"},
                        {"code": "141100", "name": "吕梁市"}],
             "150000": [{"code": "150100", "name": "呼和浩特市"}, {"code": "150200", "name": "包头市"},
                        {"code": "150300", "name": "乌海市"}, {"code": "150400", "name": "赤峰市"},
                        {"code": "150500", "name": "通辽市"}, {"code": "150600", "name": "鄂尔多斯市"},
                        {"code": "150700", "name": "呼伦贝尔市"}, {"code": "150800", "name": "巴彦淖尔市"},
                        {"code": "150900", "name": "乌兰察布市"}, {"code": "152200", "name": "兴安盟"},
                        {"code": "152500", "name": "锡林郭勒盟"}, {"code": "152900", "name": "阿拉善盟"}],
             "210000": [{"code": "210100", "name": "沈阳市"}, {"code": "210200", "name": "大连市"},
                        {"code": "210300", "name": "鞍山市"}, {"code": "210400", "name": "抚顺市"},
                        {"code": "210500", "name": "本溪市"}, {"code": "210600", "name": "丹东市"},
                        {"code": "210700", "name": "锦州市"}, {"code": "210800", "name": "营口市"},
                        {"code": "210900", "name": "阜新市"}, {"code": "211000", "name": "辽阳市"},
                        {"code": "211100", "name": "盘锦市"}, {"code": "211200", "name": "铁岭市"},
                        {"code": "211300", "name": "朝阳市"}, {"code": "211400", "name": "葫芦岛市"}],
             "220000": [{"code": "220100", "name": "长春市"}, {"code": "220200", "name": "吉林市"},
                        {"code": "220300", "name": "四平市"}, {"code": "220400", "name": "辽源市"},
                        {"code": "220500", "name": "通化市"}, {"code": "220600", "name": "白山市"},
                        {"code": "220700", "name": "松原市"}, {"code": "220800", "name": "白城市"},
                        {"code": "222400", "name": "延边朝鲜族自治州"}],
             "230000": [{"code": "230100", "name": "哈尔滨市"}, {"code": "230200", "name": "齐齐哈尔市"},
                        {"code": "230300", "name": "鸡西市"}, {"code": "230400", "name": "鹤岗市"},
                        {"code": "230500", "name": "双鸭山市"}, {"code": "230600", "name": "大庆市"},
                        {"code": "230700", "name": "伊春市"}, {"code": "230800", "name": "佳木斯市"},
                        {"code": "230900", "name": "七台河市"}, {"code": "231000", "name": "牡丹江市"},
                        {"code": "231100", "name": "黑河市"}, {"code": "231200", "name": "绥化市"},
                        {"code": "232700", "name": "大兴安岭地区"}], "310000": [{"code": "310100", "name": "直辖市"}],
             "320000": [{"code": "320100", "name": "南京市"}, {"code": "320200", "name": "无锡市"},
                        {"code": "320300", "name": "徐州市"}, {"code": "320400", "name": "常州市"},
                        {"code": "320500", "name": "苏州市"}, {"code": "320600", "name": "南通市"},
                        {"code": "320700", "name": "连云港市"}, {"code": "320800", "name": "淮安市"},
                        {"code": "320900", "name": "盐城市"}, {"code": "321000", "name": "扬州市"},
                        {"code": "321100", "name": "镇江市"}, {"code": "321200", "name": "泰州市"},
                        {"code": "321300", "name": "宿迁市"}],
             "330000": [{"code": "330100", "name": "杭州市"}, {"code": "330200", "name": "宁波市"},
                        {"code": "330300", "name": "温州市"}, {"code": "330400", "name": "嘉兴市"},
                        {"code": "330500", "name": "湖州市"}, {"code": "330600", "name": "绍兴市"},
                        {"code": "330700", "name": "金华市"}, {"code": "330800", "name": "衢州市"},
                        {"code": "330900", "name": "舟山市"}, {"code": "331000", "name": "台州市"},
                        {"code": "331100", "name": "丽水市"}],
             "340000": [{"code": "340100", "name": "合肥市"}, {"code": "340200", "name": "芜湖市"},
                        {"code": "340300", "name": "蚌埠市"}, {"code": "340400", "name": "淮南市"},
                        {"code": "340500", "name": "马鞍山市"}, {"code": "340600", "name": "淮北市"},
                        {"code": "340700", "name": "铜陵市"}, {"code": "340800", "name": "安庆市"},
                        {"code": "341000", "name": "黄山市"}, {"code": "341100", "name": "滁州市"},
                        {"code": "341200", "name": "阜阳市"}, {"code": "341300", "name": "宿州市"},
                        {"code": "341500", "name": "六安市"}, {"code": "341600", "name": "亳州市"},
                        {"code": "341700", "name": "池州市"}, {"code": "341800", "name": "宣城市"}],
             "350000": [{"code": "350100", "name": "福州市"}, {"code": "350200", "name": "厦门市"},
                        {"code": "350300", "name": "莆田市"}, {"code": "350400", "name": "三明市"},
                        {"code": "350500", "name": "泉州市"}, {"code": "350600", "name": "漳州市"},
                        {"code": "350700", "name": "南平市"}, {"code": "350800", "name": "龙岩市"},
                        {"code": "350900", "name": "宁德市"}],
             "360000": [{"code": "360100", "name": "南昌市"}, {"code": "360200", "name": "景德镇市"},
                        {"code": "360300", "name": "萍乡市"}, {"code": "360400", "name": "九江市"},
                        {"code": "360500", "name": "新余市"}, {"code": "360600", "name": "鹰潭市"},
                        {"code": "360700", "name": "赣州市"}, {"code": "360800", "name": "吉安市"},
                        {"code": "360900", "name": "宜春市"}, {"code": "361000", "name": "抚州市"},
                        {"code": "361100", "name": "上饶市"}],
             "370000": [{"code": "370100", "name": "济南市"}, {"code": "370200", "name": "青岛市"},
                        {"code": "370300", "name": "淄博市"}, {"code": "370400", "name": "枣庄市"},
                        {"code": "370500", "name": "东营市"}, {"code": "370600", "name": "烟台市"},
                        {"code": "370700", "name": "潍坊市"}, {"code": "370800", "name": "济宁市"},
                        {"code": "370900", "name": "泰安市"}, {"code": "371000", "name": "威海市"},
                        {"code": "371100", "name": "日照市"}, {"code": "371300", "name": "临沂市"},
                        {"code": "371400", "name": "德州市"}, {"code": "371500", "name": "聊城市"},
                        {"code": "371600", "name": "滨州市"}, {"code": "371700", "name": "菏泽市"}],
             "410000": [{"code": "410100", "name": "郑州市"}, {"code": "410200", "name": "开封市"},
                        {"code": "410300", "name": "洛阳市"}, {"code": "410400", "name": "平顶山市"},
                        {"code": "410500", "name": "安阳市"}, {"code": "410600", "name": "鹤壁市"},
                        {"code": "410700", "name": "新乡市"}, {"code": "410800", "name": "焦作市"},
                        {"code": "410900", "name": "濮阳市"}, {"code": "411000", "name": "许昌市"},
                        {"code": "411100", "name": "漯河市"}, {"code": "411200", "name": "三门峡市"},
                        {"code": "411300", "name": "南阳市"}, {"code": "411400", "name": "商丘市"},
                        {"code": "411500", "name": "信阳市"}, {"code": "411600", "name": "周口市"},
                        {"code": "411700", "name": "驻马店市"}],
             "420000": [{"code": "420100", "name": "武汉市"}, {"code": "420200", "name": "黄石市"},
                        {"code": "420300", "name": "十堰市"}, {"code": "420500", "name": "宜昌市"},
                        {"code": "420600", "name": "襄阳市"}, {"code": "420700", "name": "鄂州市"},
                        {"code": "420800", "name": "荆门市"}, {"code": "420900", "name": "孝感市"},
                        {"code": "421000", "name": "荆州市"}, {"code": "421100", "name": "黄冈市"},
                        {"code": "421200", "name": "咸宁市"}, {"code": "421300", "name": "随州市"},
                        {"code": "422800", "name": "恩施土家族苗族自治州"}],
             "430000": [{"code": "430100", "name": "长沙市"}, {"code": "430200", "name": "株洲市"},
                        {"code": "430300", "name": "湘潭市"}, {"code": "430400", "name": "衡阳市"},
                        {"code": "430500", "name": "邵阳市"}, {"code": "430600", "name": "岳阳市"},
                        {"code": "430700", "name": "常德市"}, {"code": "430800", "name": "张家界市"},
                        {"code": "430900", "name": "益阳市"}, {"code": "431000", "name": "郴州市"},
                        {"code": "431100", "name": "永州市"}, {"code": "431200", "name": "怀化市"},
                        {"code": "431300", "name": "娄底市"}, {"code": "433100", "name": "湘西土家族苗族自治州"}],
             "440000": [{"code": "440100", "name": "广州市"}, {"code": "440200", "name": "韶关市"},
                        {"code": "440300", "name": "深圳市"}, {"code": "440400", "name": "珠海市"},
                        {"code": "440500", "name": "汕头市"}, {"code": "440600", "name": "佛山市"},
                        {"code": "440700", "name": "江门市"}, {"code": "440800", "name": "湛江市"},
                        {"code": "440900", "name": "茂名市"}, {"code": "441200", "name": "肇庆市"},
                        {"code": "441300", "name": "惠州市"}, {"code": "441400", "name": "梅州市"},
                        {"code": "441500", "name": "汕尾市"}, {"code": "441600", "name": "河源市"},
                        {"code": "441700", "name": "阳江市"}, {"code": "441800", "name": "清远市"},
                        {"code": "441900", "name": "东莞市"}, {"code": "442000", "name": "中山市"},
                        {"code": "445100", "name": "潮州市"}, {"code": "445200", "name": "揭阳市"},
                        {"code": "445300", "name": "云浮市"}],
             "450000": [{"code": "450100", "name": "南宁市"}, {"code": "450200", "name": "柳州市"},
                        {"code": "450300", "name": "桂林市"}, {"code": "450400", "name": "梧州市"},
                        {"code": "450500", "name": "北海市"}, {"code": "450600", "name": "防城港市"},
                        {"code": "450700", "name": "钦州市"}, {"code": "450800", "name": "贵港市"},
                        {"code": "450900", "name": "玉林市"}, {"code": "451000", "name": "百色市"},
                        {"code": "451100", "name": "贺州市"}, {"code": "451200", "name": "河池市"},
                        {"code": "451300", "name": "来宾市"}, {"code": "451400", "name": "崇左市"}],
             "460000": [{"code": "460100", "name": "海口市"}, {"code": "460200", "name": "三亚市"},
                        {"code": "460300", "name": "三沙市"}, {"code": "460400", "name": "儋州市"}],
             "500000": [{"code": "500100", "name": "直辖市"}],
             "510000": [{"code": "510100", "name": "成都市"}, {"code": "510300", "name": "自贡市"},
                        {"code": "510400", "name": "攀枝花市"}, {"code": "510500", "name": "泸州市"},
                        {"code": "510600", "name": "德阳市"}, {"code": "510700", "name": "绵阳市"},
                        {"code": "510800", "name": "广元市"}, {"code": "510900", "name": "遂宁市"},
                        {"code": "511000", "name": "内江市"}, {"code": "511100", "name": "乐山市"},
                        {"code": "511300", "name": "南充市"}, {"code": "511400", "name": "眉山市"},
                        {"code": "511500", "name": "宜宾市"}, {"code": "511600", "name": "广安市"},
                        {"code": "511700", "name": "达州市"}, {"code": "511800", "name": "雅安市"},
                        {"code": "511900", "name": "巴中市"}, {"code": "512000", "name": "资阳市"},
                        {"code": "513200", "name": "阿坝藏族羌族自治州"}, {"code": "513300", "name": "甘孜藏族自治州"},
                        {"code": "513400", "name": "凉山彝族自治州"}],
             "520000": [{"code": "520100", "name": "贵阳市"}, {"code": "520200", "name": "六盘水市"},
                        {"code": "520300", "name": "遵义市"}, {"code": "520400", "name": "安顺市"},
                        {"code": "520500", "name": "毕节市"}, {"code": "520600", "name": "铜仁市"},
                        {"code": "522300", "name": "黔西南布依族苗族自治州"}, {"code": "522600", "name": "黔东南苗族侗族自治州"},
                        {"code": "522700", "name": "黔南布依族苗族自治州"}],
             "530000": [{"code": "530100", "name": "昆明市"}, {"code": "530300", "name": "曲靖市"},
                        {"code": "530400", "name": "玉溪市"}, {"code": "530500", "name": "保山市"},
                        {"code": "530600", "name": "昭通市"}, {"code": "530700", "name": "丽江市"},
                        {"code": "530800", "name": "普洱市"}, {"code": "530900", "name": "临沧市"},
                        {"code": "532300", "name": "楚雄彝族自治州"}, {"code": "532500", "name": "红河哈尼族彝族自治州"},
                        {"code": "532600", "name": "文山壮族苗族自治州"}, {"code": "532800", "name": "西双版纳傣族自治州"},
                        {"code": "532900", "name": "大理白族自治州"}, {"code": "533100", "name": "德宏傣族景颇族自治州"},
                        {"code": "533300", "name": "怒江傈僳族自治州"}, {"code": "533400", "name": "迪庆藏族自治州"}],
             "540000": [{"code": "540100", "name": "拉萨市"}, {"code": "540200", "name": "日喀则市"},
                        {"code": "540300", "name": "昌都市"}, {"code": "540400", "name": "林芝市"},
                        {"code": "540500", "name": "山南市"}, {"code": "540600", "name": "那曲市"},
                        {"code": "542500", "name": "阿里地区"}],
             "610000": [{"code": "610100", "name": "西安市"}, {"code": "610200", "name": "铜川市"},
                        {"code": "610300", "name": "宝鸡市"}, {"code": "610400", "name": "咸阳市"},
                        {"code": "610500", "name": "渭南市"}, {"code": "610600", "name": "延安市"},
                        {"code": "610700", "name": "汉中市"}, {"code": "610800", "name": "榆林市"},
                        {"code": "610900", "name": "安康市"}, {"code": "611000", "name": "商洛市"}],
             "620000": [{"code": "620100", "name": "兰州市"}, {"code": "620200", "name": "嘉峪关市"},
                        {"code": "620300", "name": "金昌市"}, {"code": "620400", "name": "白银市"},
                        {"code": "620500", "name": "天水市"}, {"code": "620600", "name": "武威市"},
                        {"code": "620700", "name": "张掖市"}, {"code": "620800", "name": "平凉市"},
                        {"code": "620900", "name": "酒泉市"}, {"code": "621000", "name": "庆阳市"},
                        {"code": "621100", "name": "定西市"}, {"code": "621200", "name": "陇南市"},
                        {"code": "622900", "name": "临夏回族自治州"}, {"code": "623000", "name": "甘南藏族自治州"}],
             "630000": [{"code": "630100", "name": "西宁市"}, {"code": "630200", "name": "海东市"},
                        {"code": "632200", "name": "海北藏族自治州"}, {"code": "632300", "name": "黄南藏族自治州"},
                        {"code": "632500", "name": "海南藏族自治州"}, {"code": "632600", "name": "果洛藏族自治州"},
                        {"code": "632700", "name": "玉树藏族自治州"}, {"code": "632800", "name": "海西蒙古族藏族自治州"}],
             "640000": [{"code": "640100", "name": "银川市"}, {"code": "640200", "name": "石嘴山市"},
                        {"code": "640300", "name": "吴忠市"}, {"code": "640400", "name": "固原市"},
                        {"code": "640500", "name": "中卫市"}],
             "650000": [{"code": "650100", "name": "乌鲁木齐市"}, {"code": "650200", "name": "克拉玛依市"},
                        {"code": "650400", "name": "吐鲁番市"}, {"code": "650500", "name": "哈密市"},
                        {"code": "652300", "name": "昌吉回族自治州"}, {"code": "652700", "name": "博尔塔拉蒙古自治州"},
                        {"code": "652800", "name": "巴音郭楞蒙古自治州"}, {"code": "652900", "name": "阿克苏地区"},
                        {"code": "653000", "name": "克孜勒苏柯尔克孜自治州"}, {"code": "653100", "name": "喀什地区"},
                        {"code": "653200", "name": "和田地区"}, {"code": "654000", "name": "伊犁哈萨克自治州"},
                        {"code": "654200", "name": "塔城地区"}, {"code": "654300", "name": "阿勒泰地区"}],
             "710000": [{"code": "710100", "name": "台北市"}, {"code": "710200", "name": "高雄市"},
                        {"code": "710300", "name": "台南市"}, {"code": "710400", "name": "台中市"},
                        {"code": "710600", "name": "南投县"}, {"code": "710700", "name": "基隆市"},
                        {"code": "710800", "name": "新竹市"}, {"code": "710900", "name": "嘉义市"},
                        {"code": "711100", "name": "新北市"}, {"code": "711200", "name": "宜兰县"},
                        {"code": "711300", "name": "新竹县"}, {"code": "711400", "name": "桃园市"},
                        {"code": "711500", "name": "苗栗县"}, {"code": "711700", "name": "彰化县"},
                        {"code": "711900", "name": "嘉义县"}, {"code": "712100", "name": "云林县"},
                        {"code": "712400", "name": "屏东县"}, {"code": "712500", "name": "台东县"},
                        {"code": "712600", "name": "花莲县"}, {"code": "712700", "name": "澎湖县"}],
             "810000": [{"code": "810100", "name": "直辖市"}], "820000": [{"code": "820100", "name": "直辖市"}]}

province_cities = {'北京市': ['北京市'],
                   '天津市': ['天津市'],
                   '河北省': ['石家庄市', '唐山市', '秦皇岛市', '邯郸市', '邢台市', '保定市', '张家口市', '承德市', '沧州市', '廊坊市', '衡水市'],
                   '山西省': ['太原市', '大同市', '阳泉市', '长治市', '晋城市', '朔州市', '晋中市', '运城市', '忻州市', '临汾市', '吕梁市'],
                   '内蒙古自治区': ['呼和浩特市', '包头市', '乌海市', '赤峰市', '通辽市', '鄂尔多斯市', '呼伦贝尔市', '巴彦淖尔市', '乌兰察布市', '兴安盟', '锡林郭勒盟',
                              '阿拉善盟'],
                   '辽宁省': ['沈阳市', '大连市', '鞍山市', '抚顺市', '本溪市', '丹东市', '锦州市', '营口市', '阜新市', '辽阳市', '盘锦市', '铁岭市', '朝阳市',
                           '葫芦岛市'], '吉林省': ['长春市', '吉林市', '四平市', '辽源市', '通化市', '白山市', '松原市', '白城市', '延边朝鲜族自治州'],
                   '黑龙江省': ['哈尔滨市', '齐齐哈尔市', '鸡西市', '鹤岗市', '双鸭山市', '大庆市', '伊春市', '佳木斯市', '七台河市', '牡丹江市', '黑河市', '绥化市',
                            '大兴安岭地区'],
                   '上海市': ['上海市'],
                   '江苏省': ['南京市', '无锡市', '徐州市', '常州市', '苏州市', '南通市', '连云港市', '淮安市', '盐城市', '扬州市', '镇江市', '泰州市', '宿迁市'],
                   '浙江省': ['杭州市', '宁波市', '温州市', '嘉兴市', '湖州市', '绍兴市', '金华市', '衢州市', '舟山市', '台州市', '丽水市'],
                   '安徽省': ['合肥市', '芜湖市', '蚌埠市', '淮南市', '马鞍山市', '淮北市', '铜陵市', '安庆市', '黄山市', '滁州市', '阜阳市', '宿州市', '六安市',
                           '亳州市', '池州市', '宣城市'],
                   '福建省': ['福州市', '厦门市', '莆田市', '三明市', '泉州市', '漳州市', '南平市', '龙岩市', '宁德市'],
                   '江西省': ['南昌市', '景德镇市', '萍乡市', '九江市', '新余市', '鹰潭市', '赣州市', '吉安市', '宜春市', '抚州市', '上饶市'],
                   '山东省': ['济南市', '青岛市', '淄博市', '枣庄市', '东营市', '烟台市', '潍坊市', '济宁市', '泰安市', '威海市', '日照市', '临沂市', '德州市',
                           '聊城市', '滨州市', '菏泽市'],
                   '河南省': ['郑州市', '开封市', '洛阳市', '平顶山市', '安阳市', '鹤壁市', '新乡市', '焦作市', '濮阳市', '许昌市', '漯河市', '三门峡市', '南阳市',
                           '商丘市', '信阳市', '周口市', '驻马店市'],
                   '湖北省': ['武汉市', '黄石市', '十堰市', '宜昌市', '襄阳市', '鄂州市', '荆门市', '孝感市', '荆州市', '黄冈市', '咸宁市', '随州市',
                           '恩施土家族苗族自治州'],
                   '湖南省': ['长沙市', '株洲市', '湘潭市', '衡阳市', '邵阳市', '岳阳市', '常德市', '张家界市', '益阳市', '郴州市', '永州市', '怀化市', '娄底市',
                           '湘西土家族苗族自治州'],
                   '广东省': ['广州市', '韶关市', '深圳市', '珠海市', '汕头市', '佛山市', '江门市', '湛江市', '茂名市', '肇庆市', '惠州市', '梅州市', '汕尾市',
                           '河源市', '阳江市', '清远市', '东莞市', '中山市', '潮州市', '揭阳市', '云浮市'],
                   '广西壮族自治区': ['南宁市', '柳州市', '桂林市', '梧州市', '北海市', '防城港市', '钦州市', '贵港市', '玉林市', '百色市', '贺州市', '河池市',
                               '来宾市', '崇左市'],
                   '海南省': ['海口市', '三亚市', '三沙市', '儋州市'],
                   '重庆市': ['重庆市'],
                   '四川省': ['成都市', '自贡市', '攀枝花市', '泸州市', '德阳市', '绵阳市', '广元市', '遂宁市', '内江市', '乐山市', '南充市', '眉山市', '宜宾市',
                           '广安市', '达州市', '雅安市', '巴中市', '资阳市', '阿坝藏族羌族自治州', '甘孜藏族自治州', '凉山彝族自治州'],
                   '贵州省': ['贵阳市', '六盘水市', '遵义市', '安顺市', '毕节市', '铜仁市', '黔西南布依族苗族自治州', '黔东南苗族侗族自治州', '黔南布依族苗族自治州'],
                   '云南省': ['昆明市', '曲靖市', '玉溪市', '保山市', '昭通市', '丽江市', '普洱市', '临沧市', '楚雄彝族自治州', '红河哈尼族彝族自治州', '文山壮族苗族自治州',
                           '西双版纳傣族自治州', '大理白族自治州', '德宏傣族景颇族自治州', '怒江傈僳族自治州', '迪庆藏族自治州'],
                   '西藏自治区': ['拉萨市', '日喀则市', '昌都市', '林芝市', '山南市', '那曲市', '阿里地区'],
                   '陕西省': ['西安市', '铜川市', '宝鸡市', '咸阳市', '渭南市', '延安市', '汉中市', '榆林市', '安康市', '商洛市'],
                   '甘肃省': ['兰州市', '嘉峪关市', '金昌市', '白银市', '天水市', '武威市', '张掖市', '平凉市', '酒泉市', '庆阳市', '定西市', '陇南市',
                           '临夏回族自治州', '甘南藏族自治州'],
                   '青海省': ['西宁市', '海东市', '海北藏族自治州', '黄南藏族自治州', '海南藏族自治州', '果洛藏族自治州', '玉树藏族自治州', '海西蒙古族藏族自治州'],
                   '宁夏回族自治区': ['银川市', '石嘴山市', '吴忠市', '固原市', '中卫市'],
                   '新疆维吾尔自治区': ['乌鲁木齐市', '克拉玛依市', '吐鲁番市', '哈密市', '昌吉回族自治州', '博尔塔拉蒙古自治州', '巴音郭楞蒙古自治州', '阿克苏地区',
                                '克孜勒苏柯尔克孜自治州', '喀什地区', '和田地区', '伊犁哈萨克自治州', '塔城地区', '阿勒泰地区'],
                   '台湾省': ['台北市', '高雄市', '台南市', '台中市', '南投县', '基隆市', '新竹市', '嘉义市', '新北市', '宜兰县', '新竹县', '桃园市', '苗栗县',
                           '彰化县', '嘉义县', '云林县', '屏东县', '台东县', '花莲县', '澎湖县'],
                   '香港特别行政区': ['香港特别行政区'],
                   '澳门特别行政区': ['澳门特别行政区']}
city_names = []
city_name_dict = {
    "北京": "北京市",
    "天津": "天津市",
    "石家庄": "石家庄市",
    "唐山": "唐山市",
    "秦皇岛": "秦皇岛市",
    "邯郸": "邯郸市",
    "邢台": "邢台市",
    "保定": "保定市",
    "张家口": "张家口市",
    "承德": "承德市",
    "沧州": "沧州市",
    "廊坊": "廊坊市",
    "衡水": "衡水市",
    "太原": "太原市",
    "大同": "大同市",
    "阳泉": "阳泉市",
    "长治": "长治市",
    "晋城": "晋城市",
    "朔州": "朔州市",
    "晋中": "晋中市",
    "运城": "运城市",
    "忻州": "忻州市",
    "临汾": "临汾市",
    "吕梁": "吕梁市",
    "呼和浩特": "呼和浩特市",
    "包头": "包头市",
    "乌海": "乌海市",
    "赤峰": "赤峰市",
    "通辽": "通辽市",
    "鄂尔多斯": "鄂尔多斯市",
    "呼伦贝尔": "呼伦贝尔市",
    "巴彦淖尔": "巴彦淖尔市",
    "乌兰察布": "乌兰察布市",
    "兴安盟": "兴安盟",
    "锡林郭勒盟": "锡林郭勒盟",
    "阿拉善盟": "阿拉善盟",
    "沈阳": "沈阳市",
    "大连": "大连市",
    "鞍山": "鞍山市",
    "抚顺": "抚顺市",
    "本溪": "本溪市",
    "丹东": "丹东市",
    "锦州": "锦州市",
    "营口": "营口市",
    "阜新": "阜新市",
    "辽阳": "辽阳市",
    "盘锦": "盘锦市",
    "铁岭": "铁岭市",
    "朝阳": "朝阳市",
    "葫芦岛": "葫芦岛市",
    "长春": "长春市",
    "吉林市": "吉林市",
    "四平": "四平市",
    "辽源": "辽源市",
    "通化": "通化市",
    "白山": "白山市",
    "松原": "松原市",
    "白城": "白城市",
    "延边": "延边朝鲜族自治州",
    "哈尔滨": "哈尔滨市",
    "齐齐哈尔": "齐齐哈尔市",
    "鸡西": "鸡西市",
    "鹤岗": "鹤岗市",
    "双鸭山": "双鸭山市",
    "大庆": "大庆市",
    "伊春": "伊春市",
    "佳木斯": "佳木斯市",
    "七台河": "七台河市",
    "牡丹江": "牡丹江市",
    "黑河": "黑河市",
    "绥化": "绥化市",
    "大兴安岭地区": "大兴安岭地区",
    "上海": "上海市",
    "南京": "南京市",
    "无锡": "无锡市",
    "徐州": "徐州市",
    "常州": "常州市",
    "苏州": "苏州市",
    "南通": "南通市",
    "连云港": "连云港市",
    "淮安": "淮安市",
    "盐城": "盐城市",
    "扬州": "扬州市",
    "镇江": "镇江市",
    "泰州": "泰州市",
    "宿迁": "宿迁市",
    "杭州": "杭州市",
    "宁波": "宁波市",
    "温州": "温州市",
    "嘉兴": "嘉兴市",
    "湖州": "湖州市",
    "绍兴": "绍兴市",
    "金华": "金华市",
    "衢州": "衢州市",
    "舟山": "舟山市",
    "台州": "台州市",
    "丽水": "丽水市",
    "合肥": "合肥市",
    "芜湖": "芜湖市",
    "蚌埠": "蚌埠市",
    "淮南": "淮南市",
    "马鞍山": "马鞍山市",
    "淮北": "淮北市",
    "铜陵": "铜陵市",
    "安庆": "安庆市",
    "黄山": "黄山市",
    "滁州": "滁州市",
    "阜阳": "阜阳市",
    "宿州": "宿州市",
    "六安": "六安市",
    "亳州": "亳州市",
    "池州": "池州市",
    "宣城": "宣城市",
    "福州": "福州市",
    "厦门": "厦门市",
    "莆田": "莆田市",
    "三明": "三明市",
    "泉州": "泉州市",
    "漳州": "漳州市",
    "南平": "南平市",
    "龙岩": "龙岩市",
    "宁德": "宁德市",
    "南昌": "南昌市",
    "景德镇": "景德镇市",
    "萍乡": "萍乡市",
    "九江": "九江市",
    "新余": "新余市",
    "鹰潭": "鹰潭市",
    "赣州": "赣州市",
    "吉安": "吉安市",
    "宜春": "宜春市",
    "抚州": "抚州市",
    "上饶": "上饶市",
    "济南": "济南市",
    "青岛": "青岛市",
    "淄博": "淄博市",
    "枣庄": "枣庄市",
    "东营": "东营市",
    "烟台": "烟台市",
    "潍坊": "潍坊市",
    "济宁": "济宁市",
    "泰安": "泰安市",
    "威海": "威海市",
    "日照": "日照市",
    "临沂": "临沂市",
    "德州": "德州市",
    "聊城": "聊城市",
    "滨州": "滨州市",
    "菏泽": "菏泽市",
    "郑州": "郑州市",
    "开封": "开封市",
    "洛阳": "洛阳市",
    "平顶山": "平顶山市",
    "安阳": "安阳市",
    "鹤壁": "鹤壁市",
    "新乡": "新乡市",
    "焦作": "焦作市",
    "濮阳": "濮阳市",
    "许昌": "许昌市",
    "漯河": "漯河市",
    "三门峡": "三门峡市",
    "南阳": "南阳市",
    "商丘": "商丘市",
    "信阳": "信阳市",
    "周口": "周口市",
    "驻马店": "驻马店市",
    "武汉": "武汉市",
    "黄石": "黄石市",
    "十堰": "十堰市",
    "宜昌": "宜昌市",
    "襄阳": "襄阳市",
    "鄂州": "鄂州市",
    "荆门": "荆门市",
    "孝感": "孝感市",
    "荆州": "荆州市",
    "黄冈": "黄冈市",
    "咸宁": "咸宁市",
    "随州": "随州市",
    "恩施": "恩施土家族苗族自治州",
    "长沙": "长沙市",
    "株洲": "株洲市",
    "湘潭": "湘潭市",
    "衡阳": "衡阳市",
    "邵阳": "邵阳市",
    "岳阳": "岳阳市",
    "常德": "常德市",
    "张家界": "张家界市",
    "益阳": "益阳市",
    "郴州": "郴州市",
    "永州": "永州市",
    "怀化": "怀化市",
    "娄底": "娄底市",
    "湘西土家族苗族自治州": "湘西土家族苗族自治州",
    "广州": "广州市",
    "韶关": "韶关市",
    "深圳": "深圳市",
    "珠海": "珠海市",
    "汕头": "汕头市",
    "佛山": "佛山市",
    "江门": "江门市",
    "湛江": "湛江市",
    "茂名": "茂名市",
    "肇庆": "肇庆市",
    "惠州": "惠州市",
    "梅州": "梅州市",
    "汕尾": "汕尾市",
    "河源": "河源市",
    "阳江": "阳江市",
    "清远": "清远市",
    "东莞": "东莞市",
    "中山": "中山市",
    "潮州": "潮州市",
    "揭阳": "揭阳市",
    "云浮": "云浮市",
    "南宁": "南宁市",
    "柳州": "柳州市",
    "桂林": "桂林市",
    "梧州": "梧州市",
    "北海": "北海市",
    "防城港": "防城港市",
    "钦州": "钦州市",
    "贵港": "贵港市",
    "玉林": "玉林市",
    "百色": "百色市",
    "贺州": "贺州市",
    "河池": "河池市",
    "来宾": "来宾市",
    "崇左": "崇左市",
    "海口": "海口市",
    "三亚": "三亚市",
    "三沙": "三沙市",
    "儋州": "儋州市",
    "重庆": "重庆市",
    "成都": "成都市",
    "自贡": "自贡市",
    "攀枝花": "攀枝花市",
    "泸州": "泸州市",
    "德阳": "德阳市",
    "绵阳": "绵阳市",
    "广元": "广元市",
    "遂宁": "遂宁市",
    "内江": "内江市",
    "乐山": "乐山市",
    "南充": "南充市",
    "眉山": "眉山市",
    "宜宾": "宜宾市",
    "广安": "广安市",
    "达州": "达州市",
    "雅安": "雅安市",
    "巴中": "巴中市",
    "资阳": "资阳市",
    "阿坝藏族羌族自治州": "阿坝藏族羌族自治州",
    "甘孜藏族自治州": "甘孜藏族自治州",
    "凉山彝族自治州": "凉山彝族自治州",
    "贵阳": "贵阳市",
    "六盘水": "六盘水市",
    "遵义": "遵义市",
    "安顺": "安顺市",
    "毕节": "毕节市",
    "铜仁": "铜仁市",
    "黔西南布依族苗族自治州": "黔西南布依族苗族自治州",
    "黔东南苗族侗族自治州": "黔东南苗族侗族自治州",
    "黔南布依族苗族自治州": "黔南布依族苗族自治州",
    "昆明": "昆明市",
    "曲靖": "曲靖市",
    "玉溪": "玉溪市",
    "保山": "保山市",
    "昭通": "昭通市",
    "丽江": "丽江市",
    "普洱": "普洱市",
    "临沧": "临沧市",
    "楚雄彝族自治州": "楚雄彝族自治州",
    "红河哈尼族彝族自治州": "红河哈尼族彝族自治州",
    "文山壮族苗族自治州": "文山壮族苗族自治州",
    "西双版纳傣族自治州": "西双版纳傣族自治州",
    "大理白族自治州": "大理白族自治州",
    "德宏傣族景颇族自治州": "德宏傣族景颇族自治州",
    "怒江傈僳族自治州": "怒江傈僳族自治州",
    "迪庆藏族自治州": "迪庆藏族自治州",
    "拉萨": "拉萨市",
    "日喀则": "日喀则市",
    "昌都": "昌都市",
    "林芝": "林芝市",
    "山南": "山南市",
    "那曲": "那曲市",
    "阿里地区": "阿里地区",
    "西安": "西安市",
    "铜川": "铜川市",
    "宝鸡": "宝鸡市",
    "咸阳": "咸阳市",
    "渭南": "渭南市",
    "延安": "延安市",
    "汉中": "汉中市",
    "榆林": "榆林市",
    "安康": "安康市",
    "商洛": "商洛市",
    "兰州": "兰州市",
    "嘉峪关": "嘉峪关市",
    "金昌": "金昌市",
    "白银": "白银市",
    "天水": "天水市",
    "武威": "武威市",
    "张掖": "张掖市",
    "平凉": "平凉市",
    "酒泉": "酒泉市",
    "庆阳": "庆阳市",
    "定西": "定西市",
    "陇南": "陇南市",
    "临夏回族自治州": "临夏回族自治州",
    "甘南藏族自治州": "甘南藏族自治州",
    "西宁": "西宁市",
    "海东": "海东市",
    "海北藏族自治州": "海北藏族自治州",
    "黄南藏族自治州": "黄南藏族自治州",
    "海南藏族自治州": "海南藏族自治州",
    "果洛藏族自治州": "果洛藏族自治州",
    "玉树藏族自治州": "玉树藏族自治州",
    "海西蒙古族藏族自治": "海西蒙古族藏族自治州",
    "银川": "银川市",
    "石嘴山": "石嘴山市",
    "吴忠": "吴忠市",
    "固原": "固原市",
    "中卫": "中卫市",
    "乌鲁木齐": "乌鲁木齐市",
    "克拉玛依": "克拉玛依市",
    "吐鲁番地区": "吐鲁番市",
    "哈密": "哈密市",
    "昌吉回族自治州": "昌吉回族自治州",
    "博尔塔拉蒙古自治州": "博尔塔拉蒙古自治州",
    "巴音郭楞蒙古自治州": "巴音郭楞蒙古自治州",
    "阿克苏地区": "阿克苏地区",
    "克孜勒苏柯尔克孜自治州": "克孜勒苏柯尔克孜自治州",
    "喀什地区": "喀什地区",
    "和田地区": "和田地区",
    "伊犁州": "伊犁哈萨克自治州",
    "塔城地区": "塔城地区",
    "阿勒泰地区": "阿勒泰地区",
    "台北": "台北市",
    "高雄": "高雄市",
    "台南": "台南市",
    "台中": "台中市",
    "南投": "南投县",
    "基隆": "基隆市",
    "新竹": "新竹县",
    "嘉义": "嘉义县",
    "新北": "新北市",
    "宜兰": "宜兰县",
    "桃园": "桃园市",
    "苗栗": "苗栗县",
    "彰化": "彰化县",
    "云林": "云林县",
    "屏东": "屏东县",
    "台东": "台东县",
    "花莲": "花莲县",
    "澎湖": "澎湖县",
    "香港": "香港特别行政区",
    "澳门": "澳门特别行政区"
}

vacc_rate_province = [
     {
        'name': '安徽省',
        'date': '2021-07-04',
        'num': 5000,
        'people_num': 6102.7171,
        'rate': '39.97%',
    },
     {
        'name': '北京市',
        # 数据日期
        'date': '2021-07-12',
        # 累计接种
        'num': 1844.76,
        # 全程接种率
        'rate': '89.39%',
    },
     {
        'name': '重庆市',
        'date': '2021-06-30',
        'num': 3205.42,
        'rate': '47.8%',
        'url': 'http://m.cq.bendibao.com/news/97366.shtm?src=people',
    },
     {
        'name': '福建省',
        'date': '2021-05-24',
        'num': 952.43,
        'people_num': 4154.0086,
        'rate': '11.18%',
    },
     {
        'name': '广东省',
        'date': '2021-07-03',
        'num': 7152.11,
        'rate': '48.48%'
    },
     {
        'name': '甘肃省',
        'date': '2021-06-08',
        'num': 1059,
        'people_num': 2501.9831,
        'rate': '20.65%',
    },
     {
        'name': '广西壮族自治区',
        'date': '2021-06-27',
        'num': 3303.28,
        'people_num': 5012.6804,
        'rate': '32.15%',
    },
     {
        'name': '贵州省',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '湖北省',
        'date': '2021-06-24',
        'num': 5015.86,
        'people_num': 5775.2557,
        'rate': '42.37%',
    },
    {
        'name': '河北省',
        'date': '',
        'num': '',
        'rate': '',
    },
    {
        'name': '黑龙江省',
        'date': '2021-06-28',
        'num': 3188,
        'people_num': 3185.0088,
        'rate': '48.83%',
    },
     {
        'name': '湖南省',
        'date': '2021-06-28',
        'num': 4697,
        'people_num': 6644.4864,
        'rate': '34.48%',
    },
    {
        'name': '河南省',
        'date': '2021-06-16',
        'num': 5000,
        'rate': '50.71%',
    },
    {
        'name': '海南省',
        'date': '2021-06-30',
        'num': 1411.5,
        'rate': '67.8%',
    },
     {
        'name': '吉林省',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '江苏省',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '江西省',
        'date': '2021-06-26',
        'num': 3144,
        'people_num': 4518.8635,
        'rate': '33.94%',
    },
     {
        'name': '辽宁省',
        'date': '2021-06-28',
        'num': 3000.44,
        'people_num': 4259.1407,
        'rate': '34.36%',
    },
   {
        'name': '内蒙古自治区',
        'date': '2021-05-14',
        'num': 360,
        'people_num': 2404.9155,
        'rate': '7.30%',
    },
     {
        'name': '宁夏回族自治区',
        'date': '2021-06-25',
        'num': 278,
        'people_num': 720.2654,
        'rate': '18.83%',
    },
     {
        'name': '青海省',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '四川省',
        'date': '2021-06-26',
        'num': 5786.73,
        'people_num': 8367.4866,
        'rate': '33.74%',
    },
     {
        'name': '山东省',
        'date': '2021-07-11',
        'num': 5570.24,
        'rate': '48.48%',
        'url': 'https://new.qq.com/omn/20210711/20210711A05JN500.html'
    },
     {
        'name': '上海市',
        'date': '2021-06-09',
        'num': 3024.92,
        'rate': '77.6%',
    },
     {
        'name': '陕西省',
        'date': '2021-06-25',
        'num': 3070,
        'people_num': 3952.8999,
        'rate': '37.89%',
    },
    {
        'name': '山西省',
        'date': '2021-06-29',
        'num': 2663.8,
        'people_num': 3491.5616,
        'rate': '37.22%',
    },
     {
        'name': '天津市',
        'date': '2021-07-02',
        'num': 948.5,
        'rate': '85%',
    },
     {
        'name': '台湾省',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '香港特别行政区',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '新疆维吾尔族自治区',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '西藏自治区',
        'date': '',
        'num': '',
        'rate': '',
    },
     {
        'name': '云南省',
        'date': '2021-06-14',
        'num': 3019.8,
        'people_num': 4720.9277,
        'rate': '31.2%',
    },
     {
        'name': '浙江省',
        'date': '2021-06-03',
        'num': 3315.2,
        'people_num': 6456.7588,
        'rate': '25.05%',
    },
]

vacc_rate_province = filter(lambda x: x.get('rate', '') != '', vacc_rate_province)
# print(list(vacc_rate_province))
vacc_rate_dict = {}
for x in vacc_rate_province:
    vacc_rate_dict[x['name']] = {'count': int(x['num']) * 10000, 'rate': x['rate'], 'update': x['date']}
# print(vacc_rate_dict
# for i in province_cities.values():
#     city_names.extend(i)
# print(dict(zip(map(lambda x:x[:-1], city_names), city_names)))
tips = [
    {
        'title': '新冠肺炎传播途径',
        'content': """·直接传播
        是指患者喷嚏、咳嗽、说话的飞沫，呼出的气体近距离直接吸入导致的感染。
        ·气溶胶传播
        是指飞沫混合在空气中，形成气溶胶，吸入后导致感染。
        ·接触传播
        是指飞沫沉积在物品表面，接触污染手后，再接触口腔、鼻腔、眼睛等粘膜，导致感染。"""
    },
    {
        'title': '疫情期间外出注意事项',
        'content': """外出采购应该就近选择附近的超市或者在营业的便利店避免乘坐公共交通工具，提前确定好采购物品，合理分配采购人员（尽量选择年轻人出门，避免老人和孩子等），减少外出人员和时间。同时在途中要远离人群密集处，保障他们的安全。 面对电梯按钮和门把手等高频接触区域，应该使用面巾纸、消毒纸等隔开，避免直接用手触碰。一旦触碰以后，及时洗手、消毒。 
        """
    },
    {
        'title': '疫情期间要注意开窗通风',
        'content': """开窗通风，有效降低空间内的致病因子浓度，太阳光直接照入室内，利用阳光中的紫外线进行消毒、杀菌，通风时长要达到30分钟。一般来说，每天开窗2—3次，每次30分钟就足够了。房间较小或感觉寒冷的情况下，开窗时间应缩短一些；房间较大、室外无风或较暖和的情况下开窗时间可以适当延长一些。早晨起床后，要及时开窗透气。最好在早中晚各开窗通风三次，每次15分钟为宜。这样既可以保持室内空气清新，又抑制了细菌滋生。"""
    },
    {
        'title': '普通公众如何选戴口罩',
        'content': """佩戴口罩，是预防新冠肺炎、流感等呼吸道传染病的有效方法，既保护自己，又保护他人。公众应根据不同疫情风险等级和所处环境选择适宜防护级别的口罩，不过分追求高防护级别。
        1.处于人员密集场所，如办公、购物、餐厅、会议室、车间、乘坐厢式电梯、公共交通工具等，应随身备用一次性使用医用口罩或医用外科口罩。
        2.有咳嗽或打喷嚏等症状者，配戴一次性使用医用口罩或医用外科口罩。
        3.与居家隔离、出院康复人员共同生活的人员，配戴一次性使用医用口罩或医用外科口罩。"""
    },
    {
        'title': '常洗手能有效减少病毒感染率',
        'content': """洗手是预防传染病最简便有效的措施之一。呼吸道传染病除了通过飞沫传播，也会经手接触传播，日常工作、生活中，人的手不断接触到被病毒、细菌污染的物品，如果不能及时正确洗手，手上的病毒、细菌可以通过手触摸口、眼、鼻进入人体。通过洗手可以简单有效地切断这一途径，保持个人手部的清洁卫生可以有效降低患呼吸道传染病的风险。
        """
    },
    {
        'title': '正确洗手的方法',
        'content': """洗手是减少手部细菌、病毒最直接有效的办法之一，正确洗手是关键。
        1. 用流动水将双手淋湿。
        2. 取适量肥皂或洗手液均匀涂抹双手。
        3. 按照“七步洗手法”认真搓洗双手至少20秒。
        """
    },
    {
        'title': '要少去人群密集的公共场所',
        'content': """公共场所人员多，流动量大，感染风险未知，且人与人之间难以保持1米距离，一旦有病毒感染者，在没有有效防护的情况下，很容易造成人与人之间的传播，空气流动性差的公共场所病毒传播的风险更大"""
    },
    {
        'title': '乘坐公共交通工具有哪些注意事项',
        'content': """1.乘坐公共交通工具前，准备好口罩、消毒湿纸巾或便携式免洗手消毒液等物品。
        2.全程佩戴口罩，尽量与他人保持1米以上的安全距离，打喷嚏、咳嗽时用纸巾或肘臂遮挡。
        3.在车站、机场、码头等要主动配合监测体温、查验健康码，尽量减少滞留时间。
        4.乘车期间，保持手卫生，尽量少碰触扶手等物体，不要用手直接接触口、眼、鼻。
        5.尽量使用扫码支付等非接触支付方式付费。
        6.乘坐公共交通工具结束后，正确洗手，确保手部卫生。"""
    },
    {
        'title': '前往超市、商场等公共场所有哪些注意事项',
        'content': """1.遵守场所管理规定，进入场所时按要求佩戴口罩，测量体温，出示健康码等。
        2.列好购物清单，尽可能减少购物逗留的时间。
        3.购物、结账时尽可能与他人保持1米以上距离，优先选择非接触扫码方式付费。
        4.乘坐电梯时，优先使用扶梯，如果必须乘坐厢式电梯，应佩戴口罩。
        5.回家后立即洗手，做好手卫生。
        """
    },
    {
        'title': '到餐厅就餐有哪些注意事项',
        'content': """1.选择间距较大，通风良好的位置落座，尽量减少多人聚餐。
        2.尽可能错峰用餐，避免人员拥挤。
        3.用餐前应规范清洁双手。
        4.2人以上用餐时，使用公筷、公勺或实行分餐制。
        5.尽量通过线上或扫码等非接触方式进行点餐和付费。"""
    },
    {
        'title': '去医院时如何做好个人防护',
        'content': """1.就诊者应提前了解就诊疗程，缩短在医院逗留的时间。
        2.全程佩戴口罩，主动配合测量体温、出示健康码、进行实名登记等。
        3.勤洗手或使用免洗手消毒剂保持手卫生，不触摸眼、口、鼻。"""
    },
    {
        'title': '要推广分餐制、使用公筷公勺',
        'content': """
        研究表明，幽门螺杆菌、甲肝病毒等消化道致病微生物可通过唾液污染筷子、勺子，进而污染食物，传染给其他就餐者。
        1.提倡多人就餐时采用分餐制、使用公筷公勺，避免个人使用过的餐具污染公共食物，可以有效降低病从口入的风险，减少交叉感染。
        2.使用公筷公勺，剩余的饭菜可以放心打包或分装，减少食物浪费    
        3.推广分餐制、使用公筷公勺是最简单有效的卫生防病习惯，是文明健康的生活方式。"""
    },
    {
        'title': '在家庭中如何实施分餐制和使用公筷公勺',
        'content': """1.固定餐具：家庭成员固定餐具，即每人使用自己的碗、筷子、勺子、水杯，从外形、颜色上加以区别。
        2.践行分餐：在每个菜盘、盆、锅等盛食物的容器上，放上公筷公勺，每个人都用公筷公勺来夹食物，用自己的碗、筷子和勺子吃饭。
        3.儿童喂养：鼓励孩子尽早独立进食。对不能进食的婴幼儿，家长或监护人要用适当的方式感觉孩子食物的温度，避免用嘴尝试孩子食物、与孩子公用餐具等。
        4.家长示范：儿童时期是培养良好习惯的关键时期，父母要为孩子做榜样，养成使用公筷公勺的好习惯，并坚持下去。
        """
    },
    {
        'title': '佩戴口罩时，有哪些注意事项',
        'content': """1.戴口罩前、摘口罩后，均应做好手卫生。
        2.区分口罩正反面，不能两面戴。
        3.不与他人混用或共用口罩。
        4.捏紧鼻夹，使口罩与脸颊贴合，避免漏气。
        5.一次性使用医用口罩和医用外科口罩均为限次使用，应定期更换。
        不建议清洗或使用消毒剂、加热等方法进行消毒后使用。"""
    },
    {
        'title': '口罩应如何保存和清洁',
        'content': """1.需重复使用的口罩，使用后悬挂于清洁、干燥的通风处，或将其放置在清洁、透气的纸袋中。口罩需单独存放，避免彼此接触，并标识口罩使用人员。
        2.备用口罩建议存放在原包装袋内，如非独立包装可存放在一次性使用食品袋中，并确保其不变形。
        3.口罩出现变湿、脏污或变形等情况后需及时更换。健康人使用后的口罩，按照生活垃圾分类的要求处理即可。"""
    },
    {
        'title': '前往室内娱乐场所应注意什么',
        'content': """室内娱乐场所主要包括电影院、歌舞厅、酒吧、健身房、游泳馆等，不仅人员聚集性强，流动性大，而且空间相对密闭，通风不良，公众前往这类场所应特别注意做好防护。
        1.配合场所实行的限流限量、预约消费、错峰入场等措施。
        2.遵守场所管理规定，进入场所时按要求佩戴口罩、测量体温、出示健康码、进行实名登记等。
        3.有序入场和退场，保持社交距离，避免拥挤。
        4.及时洗手或使用免洗手消毒剂保持手卫生。"""
    },
    {
        'title': '工作场所如何做好防护',
        'content': """1.遵守单位防疫措施和规定。
        2.配合做好体温检测。
        3.不要带病上班，出现发热等身体不适要及时向单位报告，并立即到医院就诊。
        4.在工作场所中，应做到戴口罩、勤洗手、1米社交距离、开窗通风、少聚集。
        5.乘坐电梯时注意与他人保持距离，尽量避免用手直接接触按钮。
        """
    },
    {
        'title': '学生上学应遵守哪些防护要求',
        'content': """1.学生应遵守所在学校的防疫措施和规定。
        2.按照学校要求每日监测体温并上报。
        3.随身携带一次性使用医用口罩,低风险地区校园内学生无需佩戴口罩。
        4.在校期间不串座、不串班、不打闹、少聚集。
        5.餐前、便前便后、接触垃圾后、使用体育器材等公用物品后,触摸眼、口、鼻等部位前,均要正确洗手。
        6.就餐排队时与他人保持距离，避免扎堆就餐，减少交谈。
        7.学生在上、下学途中，尽量做到家庭、学校“两点一线”，避免不必要外出活动。最好采取步行、自行车、私家车方式上下学。乘坐公共交通工具或校车时应注意个人防护，佩戴口罩，与他人保持合理距离，途中尽量不触摸公共交通工具上的物品。到校后或回家后，要及时洗手。
        8.出现发热、咳嗽等症状要及时向学校如实报告，并立即到医院就诊，严禁带病上课。"""
    },
    {
        'title': '外出不方便洗手时该怎么办',
        'content': """外出不方便洗手时，可选用含75%酒精的手消毒剂进行手部清洁，将消毒剂涂抹双手，持续揉搓15秒。
        特殊情况下，也可使用含氯或过氧化氢手消毒剂。使用时用量要足够，要让手心、手背、指缝、手腕等处充分湿润，两手相互摩擦足够长的时间，要等消毒液差不多蒸发之后再停止。
        对公众而言，不建议以免洗的手部消毒液作为常规的手部清洁手段，只是在户外等没有条件用水和肥皂洗手的时候使用。"""
    },
    {
        'title': '家庭中，怎样预防新型冠状病毒传染',
        'content': """1、增强卫生健康意识，适量运动、早睡早起、不熬夜可提高自身免疫力。
    　　2、保持良好的个人卫生习惯，咳嗽或打喷嚏时用纸巾掩住口鼻，经常彻底洗手，不用脏手摸眼睛、鼻或口。
    　　3、居室多通风换气并保持整洁卫生。
    　　4、尽可能避免与有呼吸道疾病症状（如发热、咳嗽或打喷嚏等）的人密切接触。
    　　5、密切关注发热、咳嗽等症状，出现此类症状一定要及时就近就医。
    　　6、房间通风换气；如有疑似患者，居住过的环境一定要进行清洁、消毒，新型冠状病毒对热敏感、可用75%酒精、含氯消毒剂、过氧化氢消毒液，氯仿等脂溶剂进行消毒。"""
    },

]
# for province in province_code:
#     code = province.get("code")
#     name = province.get("name")
#     cities = city_dict.get(code)
#     cities = map(lambda city: city.get("name") if city.get("name") != "直辖市" else name, cities)
#     province_cities[name] = list(cities)
# print(province_cities)
# tp = round(datetime.strptime('2021-06-30', "%Y-%m-%d").timestamp())
# print(tp)
# print(datetime.fromtimestamp(tp))
# tmp_dict = {}
# for i in province_cities.keys():
#     vs = province_cities.get(i)
#     for v in vs:
#         if tmp_dict.get(v) is not None:
#             print(v)
#         else:
#             tmp_dict[v] = 1

# dt = datetime.fromtimestamp(1625011200.0)
# print(dt)
